### ISSUE TITLE
upgrade to latest miniquad

### ISSUE THREAD

**Issue by joseluis** [nokola/nonaquad#1]
The latest recommended version of miniquad 3.0-alpha has a couple of API changes that breaks nonaquad.

Specifically, [ShaderMeta.images](https://docs.rs/miniquad/0.3.0-alpha.29/miniquad/graphics/struct.ShaderMeta.html) field is no longer `&'static [&'static str]` but `Vec<String>`, and [UniformBlockLayout.uniforms](https://docs.rs/miniquad/0.3.0-alpha.29/miniquad/graphics/struct.UniformBlockLayout.html) also went from `&'static [(&'static str, UniformType)]` to `Vec<UniformDesc>`, breaks the const [shader::META](https://github.com/nokola/nonaquad/blob/master/src/nvgimpl.rs#L100) structure.

**Comment by nokola** [comment]
Fixed!
