### ISSUE TITLE
Incorrect paths

### ISSUE THREAD

**Issue by GeTechG** [nokola/nonaquad#4]
Perhaps I'm doing something wrong, but for some reason the path is not correct.

my
![Снимок экрана от 2021-08-26 01-07-49](https://user-images.githubusercontent.com/20752579/130857776-c504a2ba-703a-40c2-ba38-1ec374a78f8a.png)

Actually, I wrote my own library for converting svg to commands, but I made the commands manually for you.

code
```rust
nona.move_to(nona::Point::new(1.7442753, 16.985759));
nona.bezier_to(nona::Point::new(1.7442753, 16.985759),
                   nona::Point::new(-15.181887000000001, 82.239445),
                   nona::Point::new(-15.878773, 83.770915));
nona.bezier_to(nona::Point::new(-16.575664, 85.302375),
                   nona::Point::new(167.51577, 84.85253300000001),
                   nona::Point::new(42.469333, 65.66409900000001));
nona.bezier_to(nona::Point::new(11.052757, 60.84321100000001),
                   nona::Point::new(71.785288, 30.93693100000001),
                   nona::Point::new(71.785288, 30.93693100000001));
```

inkscape
![Снимок экрана от 2021-08-26 01-08-32](https://user-images.githubusercontent.com/20752579/130857796-1f40d802-fdfe-47a3-8a83-5e075d99b5d2.png)
[test.svg.zip](https://github.com/nokola/nonaquad/files/7049704/test.svg.zip)

**Comment by nokola** [comment]
A little busy this week, will look in a couple of days! Thanks for letting me know!
