### ISSUE TITLE
Can I still use this rendering library if I use my own windows instead of miniquad or nonaquad windows?

### ISSUE THREAD

**Issue by cyan-river** [nokola/nonaquad#8]
Can I still use this rendering library if I use my own windows instead of miniquad or nonaquad windows?

**Comment by nokola** [comment]
Yes, as long as you implement the Renderer trait: https://github.com/nokola/nonaquad/blob/main/nona/src/renderer.rs

But I think the library is not good enough yet. I haven't worked on it for a while and not sure when I'll be able to again. I'm working on another app for note taking and wellbeing that I'd like to spend most of my time on.
I have a plan of making a very easy developer UI experience and interface for nona. However, at the moment I think it may be a mistake picking this library, unless you'd like to be a main contributor and help develop it further.

**Comment by nokola** [comment]
I added the above comment to readme.md to make sure people are more aware.

Thank you for asking about the current state and helping clarify it!

**Comment by Misaka15535** [comment]
I want to write a gui library by myself. I have learned some opengl related knowledge. The relevant code is currently being written. But with my current knowledge it is not enough to implement the Renderer trait.

While it may not be appropriate to ask this question here, I would like to ask a question about drawing.

I'm stuck on pixel coordinates now. Probably related knowledge about tailoring. Specifically, I can now draw graphics, such as four-sided rectangles. But I don't know how to draw using pixel units as position and size. Can you write an example that only draws a four-sided rectangle or explain to me the knowledge and ideas related to the implementation?

I can't find the relevant piece of knowledge I'm missing. I don't know anyone who knows about it. The implementation of this feature you wrote, though achieves the result I want. But there's a lot of nesting inside. I can't tell which code is what I need, i.e. I can't understand the code. So I can only ask you. Hope you can help me.
